services:
  postgres:
    image: postgres:15-alpine
    container_name: rtrw-postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: purboyndra # Matches your DATABASE_URL
      POSTGRES_PASSWORD: purboyndra53
      POSTGRES_DB: rtrw_app
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
